server:
  port: 8080
  application:
    name: cloudvault
  datasource:
    url: jdbc:h2:mem:cloudvault
    "driver-class-name": org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/photoslibrary.readonly
              - https://www.googleapis.com/auth/drive.readonly
test-value: ${GOOGLE_CLIENT_ID:NOT_LOADED}

# logging:
#   level:
#     org.springframework.boot: DEBUG
